### PR TITLE
Less verbose timestamps

### LINKED ISSUE #212: Make timestamps in stdout logs less verbose
`2018-07-24 16:44:28.696836 UTC` --> `2018-07-24 16:44:28`

It wastes columns and in practice we don't care about the timezone and don't need microsecond precision.

### PR DESCRIPTION
**Pull request by pelillian**
Fixed #212 
Text logs still have microsecond timestamps & timezone but stdout no longer shows them.

### CODE REVIEW

**Comment by jonashen** [comment]
Can you post an example (along with the log output printed to console) demonstrating this change?

**Comment by pelillian** [comment]
Here's an example:
```
from garage.misc import logger
logger.add_text_output("test/out.txt")
logger.log("test_logger abc")
```

test/out.txt:
2018-10-08 17:06:42.171928 PDT | test_logger abc
stdout:
2018-10-08 17:06:42 | test_logger abc

**Comment by ryanjulian** [comment]
ref #212

**Comment by ryanjulian** [comment]
Note that once a PR is approved, it's up to you to push the "Squash and merge" button.

Please carefully follow the instructions for commit messages in `CONTRIBUTING.md`

**Pull request merged**
