### PR TITLE
Reshape input in tf/cnn

### PR DESCRIPTION
**Pull request by yeukfu**
This should close https://github.com/rlworkgroup/garage/issues/2154.

In tf/cnn.py, unflatten the input if it is flattened.

### CODE REVIEW

**Comment by yeukfu** [comment]
@krzentner I have a concern that if we add env_spec into the constructor of tf/cnn_model, it will be not consistent to the torch's module.

**Review by krzentner — COMMENTED** [review]
I think that's fine. There's already other minor differences between TF and Torch in the model code.

**Comment by yeukfu** [comment]
> I think that's fine. There's already other minor differences between TF and Torch in the model code.

I pass the input_dim to the constructor of cnn models, which is more consistent the current apis I think. Because some constructors have output_dim as an argument.

**Review by krzentner — APPROVED** [review]
Nice!

**Pull request merged**
