### PR TITLE
Fix dones bug in VecEnvExecutor

### LINKED ISSUE #1435: VecEnvExecutor incorrectly copies dones array
`dones` should be a `copy.deepcopy` rather than a reference to `completes`, though changing this to a deepcopy breaks `OnPolicyVectorizedSampler` when used on nonterminating environments.

### PR DESCRIPTION
**Pull request by maliesa96**
closes #1435.

### CODE REVIEW

**Comment by maliesa96** [comment]
@mergifyio rebase

**Comment by maliesa96** [comment]
@ryanjulian I did, but @krzentner  would rather I do that after the release because removing `OffPolicyVectorizedSampler` right now would break resuming training for off-policy algos, so I just went with the simple fix for now.

**Comment by ryanjulian** [comment]
@mergifyio rebase

**Comment by ryanjulian** [comment]
@mergifyio backport release-2019.10

**Pull request merged**
