### PR TITLE
Solve #2204

### PR DESCRIPTION
**Pull request by ghost**
Solve inconsistent usage between the definition and call of the function _sample_params in cem.py.

### CODE REVIEW

**Review by krzentner — APPROVED** [review]

**Review by haydenshively — APPROVED** [review]

**Comment by haydenshively** [comment]
@krzentner Can you please merge this?

**Comment by avnishn** [comment]
@mergifyio rebase

**Comment by ziyiwu9494** [comment]
@Mergifyio rebase

**Comment by ziyiwu9494** [comment]
@os-popt  Can you make sure the commit passes the pre-commit check? [How to install and run pre-commit](https://github.com/rlworkgroup/garage/blob/56889ac141819a4c57588df80975b725a03d758b/CONTRIBUTING.md#preparing-your-repo-to-make-contributions)

**Pull request closed without merging**
