### PR TITLE
Add Double DQN

### LINKED ISSUE #1557: torch/(D)DQN
See https://arxiv.org/abs/1312.5602

### PR DESCRIPTION
**Pull request by maliesa96**
Adds Double DQN loss to torch/DQN. Closes #1557.

### CODE REVIEW

**Comment by maliesa96** [comment]
Benchmarks on Atari 10M:

image

**Review by ryanjulian — APPROVED** [review]

**Comment by ryanjulian** [comment]
Don't forget to update the docs pages with all of the DQN variants!

**Comment by maliesa96** [comment]
Will do!

**Review by irisliucy — APPROVED** [review]

**Comment by irisliucy** [comment]
Look good to me.

**Pull request merged**
