### PR TITLE
Remove  redundant entropy calculation in torch/vpg

### PR DESCRIPTION
**Pull request by igor-krawczuk**
This is a micro-PR (although I might add to it if I find other things before it is accepted). While going through the code for a project I've noticed a redundant call to the entropy calculation in the torch VPG implementation

https://github.com/rlworkgroup/garage/blob/4b204e469d6e1bd527478ad9770d27051cbbd89c/src/garage/torch/algos/vpg.py#L245

This PR simply removes the redundant call

### CODE REVIEW

**Comment by igor-krawczuk** [comment]
Hm, I didn't expect the CI to fail based on a simple line removal hence I did not set it up for this....is this a problem on the PRs side or on the CI side?

**Comment by krzentner** [comment]
It looks like the CI failed for reasons unrelated to this change. Probably due to a binary incompatibility problem between PyTorch and TensorFlow we've been dealing with on the CI for the past few weeks.

**Comment by krzentner** [comment]
@Mergifyio rebase

**Comment by krzentner** [comment]
@Mergifyio rebase

**Comment by ryanjulian** [comment]
It failed because our CI still requires a MuJoCo key is still required to run the test suite, but it isn't shared with forks for security reasons. We can pull it into a local branch to run the CI

**Comment by ryanjulian** [comment]
@Mergifyio rebase

**Comment by ryanjulian** [comment]
@igor-krawczuk sorry this hasn't been merged yet -- the garage team is working hard on a deadline this week and will return to focusing on code next week (in time for our `2020.02` release).

in the meantime, can you try to keep this branch limited to a single new feature or change? you are welcome to open other pull requests.

**Comment by ryanjulian** [comment]
@yonghyuc please do not use `git merge` or the `Update branch` button on github. It creates merge commits, which are banned in this repository. Merge commits are also likely to create a bunch of problem for you in our rebase-based workflow.

To fix this, you can use `git rebase -i origin/master` from your local machine and choose `squash` for all but the first commit.

**Comment by igor-krawczuk** [comment]
Yeah sorry,  I think it's because I accidentally kept working on the branch I used to create the pull request with. If there is still interest I'll create another PR with the original changes

**Comment by ryanjulian** [comment]
@igor-krawczuk  Yes, please.
@gitanshu was a version of this merged already?

**Pull request closed without merging**
