### PR TITLE
Copy parameters when cloning

### LINKED ISSUE #1446: Policy.clone should also copy parameters
This is not possible at the moment, because policies do not build itself. Parameters do not exist before
a network is built. Once issue #1445 is resolved, we should fix `policy.clone()` so that it also copies
parameters.

### PR DESCRIPTION
**Pull request by ahtsan**
Close #1446

### CODE REVIEW

**Comment by ahtsan** [comment]
@Mergifyio rebase

**Comment by ahtsan** [comment]
@Mergifyio rebase

**Comment by gitanshu** [comment]
@Mergifyio rebase

**Comment by ahtsan** [comment]
@Mergifyio rebase

**Comment by ahtsan** [comment]
@mergifyio rebase

**Comment by ahtsan** [comment]
@Mergifyio rebase

**Comment by ahtsan** [comment]
@Mergifyio backport release-2020.06

**Comment by ahtsan** [comment]
@Mergifyio backport release-2019.10

**Pull request merged**
