### PR TITLE
improve parameters of example her_ddpg_fetchreach

### PR DESCRIPTION
**Pull request by st2yang**
The original parameters are not working at all. The modifications try to follow the original parameters in [gym robotics paper](https://arxiv.org/pdf/1802.09464.pdf). The comparison between before and after modifications are here: [before ](https://ibb.co/Dgw1T2D), [after ](https://ibb.co/80FRg5y).

One modification I am not sure is max_path_length=250. Since the time limit of fetchreach env is 50, and use HER with k=4, then the max_path_length should be 50*(4+1) = 250?

### CODE REVIEW

**Comment by st2yang** [comment]
#1739

**Comment by ryanjulian** [comment]
@st2yang Thank you so much for the PR!

This looks great.

The CI is rejecting your PR right now because it wants you to change the commit message to conform to the guidelines [here](https://github.com/rlworkgroup/garage/blob/master/CONTRIBUTING.md#commit-message-format). It should be an easy fix with `git commit --amend`.

**Comment by st2yang** [comment]
@ryanjulian Hi, I tried to follow the commit format, but it's still not approved. Am I doing something wrong, how can I fix it?

What I did is as follows, which seems to be fine?
git commit --amend -m "tile" -m "body"
git push -f

**Comment by ryanjulian** [comment]
You can see the exact errors in Travis [here](https://travis-ci.com/github/rlworkgroup/garage/jobs/359574672#L1496) (or you can always click the travis link below to see the failing job.

relevant snippet from the logs:
```
Checking commit message for 2f6a4b0d02824daac71f9b66661991179e0f0352
Error: your subject line must be capitalized.
Error: line 1 of your body paragraph must be wrapped to 72 characters:
>> improve parameters of example her_ddpg_fetchreach; the original parameters are not working
Failing commit message:
improve her_ddpg_fetchreach parameters

improve parameters of example her_ddpg_fetchreach; the original parameters are not working
```

Basically, it wants a commit message like this
```
Improve her_ddpg_fetchreach parameters                           <-- subject line capitalized
                                                                 <-- blank line
Improve parameters of example her_ddpg_fetchreach; the original  <-- wrapped at 72 columns
parameters are not working
```

The exact guidelines are documented in [`CONTRIBUTING.md`](https://github.com/rlworkgroup/garage/blob/master/CONTRIBUTING.md#commit-message-format), which links to [this tutorial](https://chris.beams.io/posts/git-commit/) containing examples.

**Comment by st2yang** [comment]
@ryanjulian ready to merge

**Comment by ryanjulian** [comment]
@Mergifyio rebase

**Comment by ryanjulian** [comment]
@Mergifyio backport release-2019.10

**Pull request merged**
