### PR TITLE
Refactor examples/theano/ to use TheanoEnv

### PR DESCRIPTION
**Pull request by jonashen**
In `examples/theano/`, spec(env) is replaced with env.spec because all gym.env are first converted into TheanoEnv.

Ref: #165

### CODE REVIEW

**Comment by jonashen** [comment]
All the examples run. I'm not sure what you have in mind since we've refactored this three times now (all with different implementations).

**Comment by ryanjulian** [comment]
`nose2 tests/` (ignoring failing tests which aren't causes by the change

**Comment by jonashen** [comment]
I get only one error when I run `nose2 tests.algos.test_trpo`, but I am pretty certain it is not caused by this PR.

```
======================================================================
ERROR: tests.algos.test_trpo.transplant_class.<locals>.C (test_trpo_relu_nan)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jonathon/Documents/garage/garage/tests/algos/test_trpo.py", line 49, in test_trpo_relu_nan
    algo.train()
  File "/Users/jonathon/Documents/garage/garage/garage/algos/batch_polopt.py", line 128, in train
    self.optimize_policy(itr, samples_data)
  File "/Users/jonathon/Documents/garage/garage/garage/algos/npo.py", line 112, in optimize_policy
    loss_before = self.optimizer.loss(all_input_values)
  File "/Users/jonathon/Documents/garage/garage/garage/optimizers/conjugate_gradient_optimizer.py", line 240, in loss
    self._num_slices)(inputs, extra_inputs)
  File "/Users/jonathon/Documents/garage/garage/garage/misc/ext.py", line 369, in sliced_f
    slice_ret_vals = f(*(inputs_slice + non_sliced_inputs))
  File "/anaconda2/envs/garage/lib/python3.5/site-packages/theano/compile/function_module.py", line 813, in __call__
    allow_downcast=s.allow_downcast)
  File "/anaconda2/envs/garage/lib/python3.5/site-packages/theano/tensor/type.py", line 178, in filter
    data.shape))
TypeError: Bad input argument to theano function with name "/Users/jonathon/Documents/garage/garage/garage/misc/ext.py:143" at index 3 (0-based).
Backtrace when that variable is created:

  File "/anaconda2/envs/garage/lib/python3.5/unittest/case.py", line 648, in __call__
    return self.run(*args, **kwds)
  File "/anaconda2/envs/garage/lib/python3.5/unittest/case.py", line 600, in run
    testMethod()
  File "/anaconda2/envs/garage/lib/python3.5/unittest/case.py", line 1353, in runTest
    self._testFunc()
  File "/Users/jonathon/Documents/garage/garage/tests/algos/test_trpo.py", line 49, in test_trpo_relu_nan
    algo.train()
  File "/Users/jonathon/Documents/garage/garage/garage/algos/batch_polopt.py", line 122, in train
    self.init_opt()
  File "/Users/jonathon/Documents/garage/garage/garage/algos/npo.py", line 50, in init_opt
    for k in dist.dist_info_keys
  File "/Users/jonathon/Documents/garage/garage/garage/algos/npo.py", line 50, in <dictcomp>
    for k in dist.dist_info_keys
  File "/Users/jonathon/Documents/garage/garage/garage/misc/ext.py", line 151, in new_tensor
    return TT.TensorType(dtype, (False, ) * ndim)(name)
Wrong number of dimensions: expected 2, got 1 with shape (1000,).

----------------------------------------------------------------------
Ran 2 tests in 8.880s

FAILED (errors=1)
```

**Comment by ryanjulian** [comment]
Okay. My apologies for being pedantic about the tests. Yes we have tried this change 3 times, but it also broke large parts of the repo each time.

**Comment by jonashen** [comment]
I agree, I would prefer to have a finalized solution first so that we don't have to keep refactoring (and breaking) the code.

**Comment by jonashen** [comment]
Yes, I'm leaving it for now until we can come up with a finalized solution.

**Pull request merged**
