### PR TITLE
Combined backport to v2019.02.0

### LINKED ISSUE #664: Backport #659
* [x] release-2019.02
* [ ] release-2018.10

### LINKED ISSUE #748: Backport #745
* [x] v2019.02
* [ ] v2018.10

### LINKED ISSUE #750: Backport #691
* [x] v2019.02
* [ ] v2018.10

### LINKED ISSUE #751: Backport #626
* [x] v2019.02
* [ ] v2018.10

### PR DESCRIPTION
**Pull request by krzentner**
This fixes #751, fixes #664, fixes #750, and fixes #748.
I believe this is all of the backports which are practical to perform at this time.

I am still testing this change, so please do not merge it yet.

### CODE REVIEW

**Comment by krzentner** [comment]
It looks like flake8 is broken in the CI. Locally (if I set the Travis commit range), everything looks fine. If the nightly tests pass on my machine, I'll merge this (and also rebase these changes onto v2018.10).

**Comment by ryanjulian** [comment]
i think that backports like this really mess up the naive logic in check_flake8.sh. as long as flake8 passes locally, i have been force-pushing pushing backports for this reason.

we have an issue #758 to fix this for the future.

until then, as long as you say the tests and flake8 pass, i'm happy.

**Comment by krzentner** [comment]
So after poking at this PR and running various tests for a few days (far more time then I probably should have spent), I believe it doesn't break anything.
This would be much more straightforward if the base branch didn't also fail some of the nightly tests.

I'm going to merge this change, and begin attempting to backport it to 2018.10 as well.

**Comment by ryanjulian** [comment]
Awesome!

**Pull request merged**
