### PR TITLE
Remove all `log_diagnostics` calls on envs

### PR DESCRIPTION
**Pull request by gonzaiva**
The package gym.Env neither has a log_diagnostics function nor we can
ensure other envs in the future will have this function either.

### CODE REVIEW

**Comment by CatherineSue** [comment]
Em... I noticed there is a `log_diagonostics` in garage/tf/algos/batch_polopt.py, shouldn't it be removed? or the self.env.log_disgnostics in it?

**Comment by gonzaiva** [comment]
According to the #248, it's only the functions in envs.

**Comment by gonzaiva** [comment]
I meant that actually, but my reply was a little bit confusing I guess.

**Comment by ryanjulian** [comment]
Isn't this missing some files?
```sh
rjulian@tars:~/code/garage$ ag env.log_diagnostics
garage/tf/algos/batch_polopt.py
152:        # self.env.log_diagnostics(paths)

garage/envs/mujoco/maze/maze_env.py
361:            self.wrapped_env.log_diagnostics(stripped_paths, *args, **kwargs)

garage/envs/mujoco/gather/gather_env.py
481:            self.wrapped_env.log_diagnostics(

garage/envs/mujoco/randomization/randomized_env.py
53:        self._wrapped_env.log_diagnostics(paths, *args, **kwargs)

garage/envs/proxy_env.py
33:        self._wrapped_env.log_diagnostics(paths, *args, **kwargs)

garage/algos/cem.py
174:            self.env.log_diagnostics(paths)

garage/algos/cma_es.py
131:            self.env.log_diagnostics(infos)

garage/theano/algos/ddpg.py
390:        self.env.log_diagnostics(paths)
```

**Comment by gonzaiva** [comment]
Ups, sorry, I just noticed I only added one file to the change.

**Comment by gonzaiva** [comment]
I just noticed that the change at 8b0aeccaa6303a0 that you merged Ryan already removes log_diagnostics. It's true that there are some log_diagnostics remaining in these files:
```
garage/envs/mujoco/gather/gather_env.py:479: self.wrapped_env.log_diagnostics(
garage/envs/mujoco/maze/maze_env.py:363: self.wrapped_env.log_diagnostics(stripped_paths, *args, **kwargs)
garage/envs/mujoco/randomization/randomized_env.py:53: self._wrapped_env.log_diagnostics(paths, *args, **kwargs)
```
I'm not sure to remove them as they're called within the definition of log_diagnostics in the corresponding environments and we agree on leaving the definitions intact.
If you agree in not removing them, then I will close the PR as no more changes are required.

**Comment by gonzaiva** [comment]
I can comment them as well.

**Comment by ryanjulian** [comment]
This looks fine. We can close this PR and the issue.

**Pull request closed without merging**
