### PR TITLE
Log all experiment start info to experiment.json

### PR DESCRIPTION
**Pull request by krzentner**
This is an initial shot at addressing #1785. It already helped me find a bug, so I think it's pretty worthwhile.

### CODE REVIEW

**Comment by krzentner** [comment]
Example resulting file in this gist: https://gist.github.com/krzentner/1b30f48286377908751da511f266544f

**Review by ryanjulian — APPROVED** [review]
Sample output?

**Comment by ryanjulian** [comment]
Perhaps we should just put this all into variant.json? Having one seems better than 2, if there aren't compelling reasons to separate them.

**Comment by maliesa96** [comment]
Is the above example still valid?

**Review by maliesa96 — APPROVED** [review]

**Review by ryanjulian — APPROVED** [review]
LGTM -- perhaps this should go into experiment.json or trainer.json?

**Pull request merged**
