### PR TITLE
Initialise GCP bucket only when needed

### LINKED ISSUE #1596: garage_benchmark can not run without Google Cloud credential
By default, log files in benchmark will not upload to GCP storage. However, now garage_benchmark cannot run without GCP credential, and will get errors like `google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials.` @gitanshu finds this is because of [this line](https://github.com/rlworkgroup/garage/blob/36f8fbaea5ff304fa3bfea2951d4b9ad3637825f/benchmarks/src/garage_benchmarks/helper.py#L48). This line shoud be moved into `_upload_to_gcp_storage` function.

### PR DESCRIPTION
**Pull request by gitanshu**
closes #1596

### CODE REVIEW

**Comment by gitanshu** [comment]
@mergifyio rebase

**Comment by krzentner** [comment]
@mergifyio rebase

**Comment by ryanjulian** [comment]
@Mergifyio rebase

**Comment by gitanshu** [comment]
@Mergifyio rebase

**Pull request merged**
