### PR TITLE
Make wrap_experiment archive the launcher repo

### PR DESCRIPTION
**Pull request by krzentner**
Also, save metadata.json and fix the wrapping logic so that click and
clize work.

### CODE REVIEW

**Comment by krzentner** [comment]
Right now, this might be useful to @naeioi and @yonghyuc (or anyone else using `wrap_experiment`), since it automatically creates `metadata.json`.

**Comment by krzentner** [comment]
> Does this archive only tracked files? What if someone has a dirty repo?

It archives tracked and untracked files, but not ignored files (those matched by `.gitignore`).

**Comment by ryanjulian** [comment]
Perfect -- and it finds the nearest git repo in my parent directory tree?

**Comment by krzentner** [comment]
> Perfect -- and it finds the nearest git repo in my parent directory tree?

Yeah. Basically, it uses `__main__.__file__` to find the launcher script, then `git rev-parse --show-toplevel` from the same directory as that script to find the "nearest" git repo of the launcher, and archives all of the non-ignored files.

**Comment by krzentner** [comment]
Unfortunately, the `git archive` command cannot archive files that haven't been added to the repo yet, so it uses `git ls-files` and `tar` manually. I'll add a comment clarifying that and some tests.

**Pull request merged**
