### PR TITLE
Refactor ContinuousMLPBaseline

### PR DESCRIPTION
**Pull request by yeukfu**
#1630

### CODE REVIEW

**Comment by ahtsan** [comment]
Is there an integration test that makes sure this baseline works as expected?

**Comment by yeukfu** [comment]
> Is there an integration test that makes sure this baseline works as expected?

There are some testcases in `test_continuous_mlp_baseline.py`. What do you mean by integration tests? `test_ppo.py` has testcases using this baseline.

**Comment by ahtsan** [comment]
> > Is there an integration test that makes sure this baseline works as expected?
> 
> There are some testcases in `test_continuous_mlp_baseline.py`. What do you mean by integration tests? `test_ppo.py` has testcases using this baseline.

That would be good enough.

**Comment by ahtsan** [comment]
@Mergifyio rebase

**Comment by ryanjulian** [comment]
@Mergifyio refresh

**Pull request merged**
