### PR TITLE
Make wrap_exp's archiving handle deleted files

### PR DESCRIPTION
**Pull request by krzentner**
Without this, tar complains that the file was deleted.
I also made it skip archiving files larger than eight mebibytes, since
that's basically never source code.

### CODE REVIEW

**Comment by zequnyu** [comment]
@Mergifyio rebase

**Comment by krzentner** [comment]
@Mergifyio rebase

**Comment by ryanjulian** [comment]
@Mergifyio rebase

**Comment by krzentner** [comment]
I've updated the tests to cover every line, but I'm not sure if codecov can detect that, since I need to spawn a subprocess to test archiving.

**Pull request merged**
