### PR TITLE
Fix spec(env) implementation

### PR DESCRIPTION
**Pull request by jonashen**
spec(env) now returns garage.Spaces, and the algorithms using env_spec are updated accordingly to treat them as garage.Spaces.

Ref: #133

### CODE REVIEW

**Comment by ryanjulian** [comment]
Does this not also affect the tf tree?

**Comment by ryanjulian** [comment]
Why not do the same in the theano tree?

**Comment by jonashen** [comment]
We can do that, but it will require a lot more refactoring. I was under the impression to get all the examples working first, and the refactor will be addressed in another PR.

**Comment by ryanjulian** [comment]
Okay, please file a bug for the refactor.

**Pull request merged**
