### PR TITLE
Move garage.misc.instrument to garage.experiment

### PR DESCRIPTION
**Pull request by jonashen**
Fixes: #383.

### CODE REVIEW

**Comment by ryanjulian** [comment]
I think it is arguable that nb_utils belongs here (either here or in `garage.logger`).

Please update #358 once you're done.

**Comment by jonashen** [comment]
If nb_utils is not used anywhere in garage, should I just delete the file or move it to garage.experiment.nb_utils

**Comment by ryanjulian** [comment]
What is the blocker here? Still the PEP8 conflicts? There

**Comment by jonashen** [comment]
Removed PEP8 conflicts. Ready for another check.

**Pull request merged**
