### PR TITLE
Fix warning regarding ABC import from collections

### PR DESCRIPTION
**Pull request by tirkarthi**
Import from collections.abc instead of collections which has been deprecated and will be removed in future.

### CODE REVIEW

**Comment by ryanjulian** [comment]
@tirkarthi thank you for this PR! @haydenshively since you are tree sheriff this week, please shepherd this through the merge process. GH actions doesn't yet support PRs from outside rlworkgroup, so you will need me or @krzentner to force-push it when it's ready.

**Review by ryanjulian — APPROVED** [review]

**Review by haydenshively — APPROVED** [review]

**Comment by haydenshively** [comment]
I'll run tests locally and let you know if/when everything passes

**Comment by haydenshively** [comment]
Everything passed except `spec19` in `test_all_gym_envs`, which seems unrelated to this change

**Comment by ryanjulian** [comment]
@mergifyio rebase

**Comment by ryanjulian** [comment]
@mergifyio rebase

**Comment by ryanjulian** [comment]
@mergifyio rebase

**Pull request merged**
