### PR TITLE
Add default sampler class to algorithms 

### PR DESCRIPTION
**Pull request by zequnyu**
#829.

### CODE REVIEW

**Comment by krzentner** [comment]
Please also note in the `RLAlgorithm` (in `src/garage/np/algos/base.py`) docstring that this field is required if `sampler_cls` isn't specified to the runner.

Unfortunately, abstract properties are a huge pain to use in Python, since they actually require using `@property`, so we probably shouldn't use one.

**Comment by krzentner** [comment]
Also, yeah. The fact that our generic `np` algorithm classes import TensorFlow samplers indicates to me that we need to do more to separate the TensorFlow setup logic from the samplers. That's out of scope for this change though.

**Comment by zequnyu** [comment]
Yes, after looking at our tf-samplers, I think we could move them all to general `samplers/`, except the recently added Ray sampler.

**Comment by zequnyu** [comment]
Actually, current implementation of policies use a lot of `@property`, would you explain why we shouldn't use it? @krzentner

**Comment by krzentner** [comment]
We do use `@property` a lot, and that's fine. The issue I have with `@abc.abstractproperty` is that it requires you to use `@property` in the implementation class, even if you don't want to.

On the topic of the samplers being TF specific, as far as I can tell the only reason they're TF specific is that they set up a `tf.Session`. However, the logic for how to correctly set up global state like that is also owned by the runner. I feel like we could solve all of this if the runner gave the sampler a "set up global environment" callback to invoke in its workers. That's probably out of scope for this PR, but should be pretty easy to implement.

**Pull request merged**
