### PR TITLE
Set TotalEnvSteps as the default Tensorboard x-axis

### PR DESCRIPTION
**Pull request by naeioi**
This PR sets `TotalEnvSteps` as the default tensorboard scalar log x-axis. This PR depends on https://github.com/rlworkgroup/dowel/pull/38.

### CODE REVIEW

**Comment by ryanjulian** [comment]
We need to merge the dowel changes first, release a dowel version, then bump the version in garage.

**Comment by naeioi** [comment]
This PR will be ready when dowel 0.0.3 is tagged.

**Comment by ryanjulian** [comment]
Let me know when this is ready and I will force-push it.

**Comment by naeioi** [comment]
@ryanjulian If we don't care about the codedev, then this should be ready. 
The uncovered code was the serializer in the experiment wrapper.

**Pull request merged**
