### PR TITLE
Add python 3.8 in metadata

### PR DESCRIPTION
**Pull request by gitanshu**
Except for an issue with mocking, which shouldn't affect usability, everything else seems to work fine. 

https://github.com/rlworkgroup/garage/actions/runs/336779170

### CODE REVIEW

**Review by ryanjulian — APPROVED** [review]
Shouldn't you change the Python version in the CI to 3.8?

**Review by yeukfu — APPROVED** [review]

**Comment by gitanshu** [comment]
> Shouldn't you change the Python version in the CI to 3.8?

The CI should use the lowest supported version, right?

**Comment by ryanjulian** [comment]
Good point, you're right.

**Comment by gitanshu** [comment]
@mergifyio rebase

**Comment by gitanshu** [comment]
@mergifyio refresh

**Pull request merged**
