### PR TITLE
Fixup between LocalTFRunner and Ray Sampler PRs

### PR DESCRIPTION
**Pull request by krzentner**
I merged the Ray Sampler without updating because of LocalTFRunner
changes. This fixes the broken example (and does some minor cleanup).

### CODE REVIEW

**Comment by krzentner** [comment]
Okay, this version the tests pass and the example runs with Ray 0.7.3.

**Comment by krzentner** [comment]
> Okay, this version the tests pass and the example runs with Ray 0.7.3.

To be clear, this version also works on 0.7.2. However, on current master the tests don't pass using Ray 0.7.3.

**Comment by avnishn** [comment]
@krzentner The CI passed on your most recent commit:
https://codecov.io/gh/rlworkgroup/garage/commit/290cfbdace1ff8e185d5b16de007fc71ef31bacc

**Comment by krzentner** [comment]
Okay, all tests pass, this fixes master, and I have two contributor approvals. I'm merging this.

**Pull request merged**
