### PR TITLE
Benchmark continuous mlp regressor/baseline

### LINKED ISSUE #883: Refactor ContinuousMLPBaseline & ContinuousMLPRegressor to use garage.tf.Model
- ContinuousMLPBaseline
- ContinuousMLPRegressor

### PR DESCRIPTION
**Pull request by avnishn**
This PR is to fully integrate the continuous mlp baseline/regressor with the model primitive. 

Included are
- A transition test
- A fix for the formerly not working continuous mlp regressor without baseline, which previously was maximizing the difference between the expected return and actual return, NOT minimizing it.
- A benchmark test that shows that the average returns are almost the same, if not better with the model primitive.

closes #883

### CODE REVIEW

**Comment by avnishn** [comment]
# Half Cheetah
PPO_CMB_Half_cheetah
# Hopper
PPO_CMB_Hopper
# Inverted Double Pendulum
PPO_CMB_Inverted_Double_Pendulum
# Inverted Pendulum 
PPO_CMB_Inverted_Pendulum_2
# Swimmer
PPO_CMB_Swimmer
# walker
PPO_CMB_Walker

**Comment by ryanjulian** [comment]
Can you post matplotlib plots, as generated by the scripts in tests/benchmarks, like the other PRs are doing? These tensorboard, plots are tiny and don't have a key we can use to compare the runs.

**Comment by avnishn** [comment]
## Cheetah Averaged over random 5 random seeds per baseline.

PPO_continuous_mlp_with_without_model

**Comment by avnishn** [comment]
closed by #898

**Pull request closed without merging**
