### PR TITLE
Use Lasagne directly instead of a private fork

### PR DESCRIPTION
**Pull request by jonashen**
This PR fixes a tuple() to int() comparison bug that resulted in `tests.test_networks` and `tests.test_algos` failing. Furthermore, this bug fix enables us to install Lasagne directly rather than a private fork. 

Note: if we want to use the latest version of Lasagne we will need to clone Lasagne into `rlworkgroup/Lasagne` and address [this](https://github.com/Lasagne/Lasagne/issues/867) issue using a new commit. However, this is beyond the scope of this PR.

Ref: #182, #184, #214

### CODE REVIEW

**Comment by ryanjulian** [comment]
If we merge this shouldn't we be able to just clone directly from https://github.com/Lasagne/Lasagne

**Comment by jonashen** [comment]
Again, like I mentioned there is a compatibility issue with the most updated version of Lasagne. It requires Theano's version to be [0.8.2](https://github.com/Lasagne/Lasagne/blob/master/requirements.txt), but we are currently using `1.0.2`. That is why we will have to fix this [issue](https://github.com/Lasagne/Lasagne/issues/867) in a private Lasagne fork.

**Comment by ryanjulian** [comment]
How many usages are there of the deprecated API?

**Comment by jonashen** [comment]
The deprecated API is used within Lasagne itself inside `lasagne/layers/pool.py` when it tries to `from theano.tensor.signal import downsample`. So basically, wherever Lasagne is used this error will occur.

**Comment by ryanjulian** [comment]
Does it work if we use bleeding-edge lasagne, as the author suggests?

**Comment by ryanjulian** [comment]
It's fixed in lasagne/master. Let's just pin to `a61b76fd991f84c50acdb7bea02118899b5fefe1`

**Comment by jonashen** [comment]
got it

**Comment by ryanjulian** [comment]
Does this close any issues?

**Comment by jonashen** [comment]
#182, #184 were already closed, just closed #214

**Pull request merged**
