### PR TITLE
xrange -> range rename

### PR DESCRIPTION
**Pull request by Maltimore**
Renamed xrange to range in the docs. xrange is only used in python 2 as far as I know.

### CODE REVIEW

**Comment by naeioi** [comment]
It looks like CI rejects changes to rst docs. @gitanshu Do you have any idea about this?

**Comment by naeioi** [comment]
Hi Maltimore. Thanks for pointing this out. Yes, `xrange` is deprecated in python3. Can you reword you commit so that its title starts with capitalized letter? e.g. `Rename xrange to range in docs`. We have a travis check on this.

**Comment by ryanjulian** [comment]
@naeioi the CI is failing because of the commit message and #653. As soon as the tests pass locally, we can pull it into a branch so it can be tested and auto-merged.

**Comment by ryanjulian** [comment]
@Maltimore as in #1056, this one is failing pre-commit checks due to your commit message. Please amend your commit message and then we can pull this in an submit it!

**Comment by Maltimore** [comment]
I amended the commit message and rebased on master. No idea why the tests are failing now, maybe because:
> @naeioi the CI is failing because of the commit message and #653. As soon as the tests pass locally, we can pull it into a branch so it can be tested and auto-merged.

**Comment by avnishn** [comment]
@Maltimore it seems that the CI crashed while we were running our tests (this happens sometimes). I've triggered your tests to run again.

**Comment by ryanjulian** [comment]
See #1072 for the merge PR.

**Pull request closed without merging**
