### PR TITLE
Auto generate docs from docstrings

### LINKED ISSUE #647: Fix documentation generation
See https://github.com/rlworkgroup/akro for an example.

A lot of the existing documentation template is kind of non-applicable, so it would be fine to delete the existing templates (not the documentation itself) and start over with the template from akro.

### PR DESCRIPTION
**Pull request by gitanshu**
closes #647

### CODE REVIEW

**Comment by ryanjulian** [comment]
hmm this doesn't seem to be totally working. for instance, `cnn_model` doesn't actually have any docs: https://garage.readthedocs.io/en/fix_api_doc/_apidoc/garage.tf.models.cnn_model.html

**Comment by gitanshu** [comment]
Yeah something's off. A lot of them are turning up empty. Will look into it

**Comment by ryanjulian** [comment]
Yeah, it looks like everything passes CI, but the API docs are still missing for many modules.

**Comment by ryanjulian** [comment]
Unfortunately the automated API docs are still incomplete. Also, see #755 which is new.

I propose we close both issues using this PR.

**Comment by gitanshu** [comment]
This is being done on fix_doc_gen branch now, opening a PR for that

**Pull request closed without merging**
