### PR TITLE
Fix pipenv install on CI

### PR DESCRIPTION
**Pull request by gitanshu**

### CODE REVIEW

**Comment by ryanjulian** [comment]
Wow, I can't believe this is all that happened.

**Comment by gitanshu** [comment]
Yeah pipenv takes much longer to lock now since the dependency resolver is stricter. 

But the test job didn't even run pipenv? :confused:

**Comment by ryanjulian** [comment]
Did you rebase on master? I disabled the pipenv check

**Comment by gitanshu** [comment]
I didn't rebase. This branch doesn't have that commit

**Comment by ryanjulian** [comment]
@mergifyio backport release-2019.10

**Pull request merged**
