### PR TITLE
 Refactor TRPO auto benchmark script

### PR DESCRIPTION
**Pull request by zequnyu**
Following #1307.

### CODE REVIEW

**Comment by avnishn** [comment]
I know someone before was saying that pytest wasn't the way to go for auto benchmarking, but I feel like it provides a seamless way to manage running many experiments. We could write the infrastructure ourselves (it's minimal) but then we would have to maintain it.

Reasons I could see us writing the infrastructure ourselves includes the possibility that pytest reduces runtime performance, or introduces not easy to manage bugs that are caused by xdist. I don't see the latter issuer occuring but potentially, the former. I guess we won't know till we test it all.

**Comment by zequnyu** [comment]
Agree. I thought about it last night and I'm totally ok with the current status. And it's probably easier to use pytest mark to control these tests, since all you need to trigger is `pytest -m benchmark`.

**Comment by ryanjulian** [comment]
Ah but there's a couple problems with this logic in the case of benchmarking all of garage (e.g. the autobenchmark project)

1. pytest isn't designed for "tests" which run for hours or days -- the 95th percentile pytest case runs in a fraction of a second.
1. It has no provision for restarting a test which is interrupted. In this extremely rare case, you're assumed to just restart the test. This might be a deal-breaker for benchmarking.
1. No first-class distributed features. There exist plug-ins (e.g. xdist) for distributing test jobs across machines, but they are not a first-class feature and, again, they are designed to farm *many very short tests* across *few hosts*, not *few very very long tests* across *few hosts*.

I'm not saying pytest is bad, just that it doesn't bring a lot to the table. If you imagine kicking off the auto benchmarking suite by running `pytest -m benchmark`, I think you will quickly find this makes things unnecessarily hard and requires lots of stupid workarounds, and for what?

It seems what you like here is that you can quickly enumerate all the benchmarks by asking pytest to go discover tests marked with `benchmark`. We can duplicate this feature easily, e.g.

* by just putting all the benchmark scripts in a directory tree, and assuming every script in that tree is a benchmark, of if you want to put benchmark scripts in a arbitrary locations...
* keeping a manifest (file with a list) of all current benchmark scripts
* writing our own discovery script which looks for a special-purpose comment, mark, file name, etc., which would be like ~10 lines of bash in a Makefile

I understand you are hungry for something to catalog/discover/track all of the possible benchmark jobs, then supervise them as they run. You're right, this is a key element of this project -- but pytest really isn't a solution. There are many possibilities which would require a similar amount of work or less. These are generally called workflow managers -- they come in many flavors.

* CIs: TravisCI, Azure Pipelines, GitLab CI, GitHub Actions, CircleCI, Jenkins, TeamCity, etc. -- note that many of these (including Azure and Github Actions) will manage/track your jobs using the cloud service, but let you setup your local machines to actually run the jobs. 
* Cluster managers: slurm, kubernetes, etc.
* ML-specific solutions: ray tune, etc.
* Pipeline managers: Apache Airflow, etc. e.g. see https://github.com/pditommaso/awesome-pipeline

Many people have the problem of "I have x work, y machines, and want to figure out which xs to put on which ys and get all the results," so the design space is huge. This is part of what makes this project fun!

**Comment by krzentner** [comment]
This looks good. I think it would also be fine to have each experiment definition in its own file in a directory, and have a single test / script to run all of them.

We already do this for examples, so it shouldn't be too complicated.

No matter what we do next, I think this is a step in the right direction.

**Pull request merged**
