### PR TITLE
Refactor GaussianMLPBaseline

### PR DESCRIPTION
**Pull request by yeukfu**
#1630 
Below are the results of benchmarks with this [experiment](https://github.com/rlworkgroup/garage/blob/master/benchmarks/src/garage_benchmarks/experiments/baselines/gaussian_mlp_baseline.py).
- 5 same seeds:
HalfCheetah-v2
Hopper-v2

- 3 different seeds:
HalfCheetah-v2
Hopper-v2
InvertedDoublePendulum-v2
InvertedPendulum-v2
Swimmer-v2
Walker2d-v2

### CODE REVIEW

**Comment by yeukfu** [comment]
> Can you also benchmark for this change?

Sure, will do.

**Comment by yeukfu** [comment]
@ahtsan The results of benchmarks are ready in the first comment.

**Comment by ryanjulian** [comment]
@yeukfu how many seeds do the benchmarks have?

**Comment by yeukfu** [comment]
> @yeukfu how many seeds do the benchmarks have?

3 seeds.

**Comment by ryanjulian** [comment]
Can you run 5 or 10 for Hopper and HalfCheetah? I think it is probably seed-dependence, but I want to double-check.

**Comment by yeukfu** [comment]
> Can you run 5 or 10 for Hopper and HalfCheetah? I think it is probably seed-dependence, but I want to double-check.

Do I need to run with the same seeds? The benchmark shown use different seeds for the two baselines.

**Comment by ryanjulian** [comment]
@yeukfu it's essential that you use the same seed for both baselines, so that they experience the same sequence of random numbers. that is "run n seeds" means "choose seeds i = 1...n, then run n experiments. in each experiment, set the seed of BOTH baselines to i"

if you didn't do that before, i think it's sufficient to run 5 seeds for both HalfCheetah and Hopper.

**Comment by yeukfu** [comment]
> @yeukfu it's essential that you use the same seed for both baselines, so that they experience the same sequence of random numbers. that is "run n seeds" means "choose seeds i = 1...n, then run n experiments. in each experiment, set the seed of BOTH baselines to i"
> 
> if you didn't do that before, i think it's sufficient to run 5 seeds for both HalfCheetah and Hopper.

Got it. I Have add the new results.

**Comment by ryanjulian** [comment]
Looks good to me! Thanks for the updated plots!

**Comment by ryanjulian** [comment]
@Mergifyio rebase

**Pull request merged**
