### PR TITLE
Fix duplicate window rendering for Plotter

### PR DESCRIPTION
**Pull request by zequnyu**
#1034

Tested locally on my Ubuntu 18.04.

### CODE REVIEW

**Comment by zequnyu** [comment]
The code is outdated and not being used anywhere. I'm trying to figure its usage and what needs to be updated.

**Comment by ryanjulian** [comment]
@zequnyu it should be used if you start any example from np/torch with a plotter...

**Comment by zequnyu** [comment]
@ryanjulian Yes, I just realised LocalRunner is actually using tf plotter. I'll try to refactor.

**Comment by ryanjulian** [comment]
@Mergifyio rebase

**Comment by ryanjulian** [comment]
@Mergifyio backport release-2019.10

**Comment by ryanjulian** [comment]
@zequnyu can you please manually backport this to release-2019.10?

**Pull request merged**
