### PR TITLE
Explicitly set codecov ci to travis-ci.com

### PR DESCRIPTION
**Pull request by krzentner**

### CODE REVIEW

**Comment by krzentner** [comment]
Let's see if this results in correct build links, at least.

**Comment by gitanshu** [comment]
The links in codecov still go to travis-ci.org :disappointed:

**Comment by krzentner** [comment]
I sent a bug report to codecov: https://community.codecov.io/t/when-codecov-ci-is-set-to-travis-ci-com-build-links-point-to-travis-ci-org-and-are-broken/1329

**Comment by ryanjulian** [comment]
FYI I believe you can also open a full-on support request, rather than hoping someone comes upon your Discourse post.

**Comment by ryanjulian** [comment]
@krzentner did this seem to fix early reporting at least?

**Comment by ryanjulian** [comment]
@Mergifyio rebase

**Comment by ryanjulian** [comment]
@Mergifyio rebase

**Comment by krzentner** [comment]
I don't know if this fixed early reporting. I didn't see any early reporting, but I didn't watch too closely.

**Comment by ryanjulian** [comment]
probably worth just merging it and see if it helps

**Comment by krzentner** [comment]
@Mergifyio rebase

**Comment by ryanjulian** [comment]
@Mergifyio refresh

**Pull request merged**
