### PR TITLE
Remove flaky marks on integration tests

### PR DESCRIPTION
**Pull request by lywong92**
Testing out if `test_ppo_memorize_digits` and `test_trpo_cubecrash` are working.

### CODE REVIEW

**Comment by lywong92** [comment]
I looked at the logs and I see the error: 
```
[gw0] PASSED tests/integration_tests/test_examples.py::test_trpo_cubecrash *** Aborted at 1583198965 (unix time) try "date -d @1583198965" if you are using GNU date ***
*** Aborted at 1583198965 (unix time) try "date -d @1583198965" if you are using GNU date ***
*** Aborted at 1583198965 (unix time) try "date -d @1583198965" if you are using GNU date ***
*** Aborted at 1583198965 (unix time) try "date -d @1583198965" if you are using GNU date ***
*** Aborted at 1583198965 (unix time) try "date -d @1583198965" if you are using GNU date ***
*** Aborted at 1583198965 (unix time) try "date -d @1583198965" if you are using GNU date ***
*** Aborted at 1583198965 (unix time) try "date -d @1583198965" if you are using GNU date ***
*** Aborted at 1583198965 (unix time) try "date -d @1583198965" if you are using GNU date ***
*** Aborted at 1583198965 (unix time) try "date -d @1583198965" if you are using GNU date ***
*** Aborted at 1583198965 (unix time) try "date -d @1583198965" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGTERM (@0x17) received by PID 651 (TID 0x7f48d262e740) from PID 23; stack trace: ***
PC: @                0x0 (unknown)
PC: @                0x0 (unknown)
PC: @                0x0 (unknown)
PC: @                0x0 (unknown)
*** SIGTERM (@0x17) received by PID 645 (TID 0x7f48d262e740) from PID 23; stack trace: ***
*** SIGTERM (@0x17) received by PID 643 (TID 0x7f48d262e740) from PID 23; stack trace: ***
*** SIGTERM (@0x17) received by PID 646 (TID 0x7f48d262e740) from PID 23; stack trace: ***
*** SIGTERM (@0x17) received by PID 642 (TID 0x7f48d262e740) from PID 23; stack trace: ***
    @     0x7f48d1dd4f20 (unknown)
    @           0x50c720 _PyEval_EvalFrameDefault
    @           0x509d48 (unknown)
    @           0x50aa7d (unknown)
    @           0x50c5b9 _PyEval_EvalFrameDefault
    @           0x508245 (unknown)
    @           0x50a080 (unknown)
    @           0x50aa7d (unknown)
    @           0x50c5b9 _PyEval_EvalFrameDefault
    @           0x509d48 (unknown)
    @           0x50aa7d (unknown)
    @           0x50c5b9 _PyEval_EvalFrameDefault
    @           0x509d48 (unknown)
    @           0x50aa7d (unknown)
    @           0x50c5b9 _PyEval_EvalFrameDefault
    @           0x509d48 (unknown)
    @           0x50aa7d (unknown)
    @           0x50c5b9 _PyEval_EvalFrameDefault
    @           0x509d48 (unknown)
    @           0x50aa7d (unknown)
```
I tried googling but can't seem to find anything useful. Any idea how I can debug this? @ryanjulian @krzentner @gitanshu

**Comment by ryanjulian** [comment]
I suspect this might be a simple out-of-memory error. 

Two options to try this hypothesis:
1) Run locally and track usage https://stackoverflow.com/questions/42809500/how-to-find-max-memory-from-docker-stats
2) Modify the `docker run` command in the`run-ci` target in the `Makefile` to limit your usage to what TravisCI supports (7.5GB, see here: https://docs.docker.com/config/containers/resource_constraints/#limit-a-containers-access-to-memory)

**Comment by avnishn** [comment]
@mergifyio rebase

**Comment by avnishn** [comment]
@mergifyio rebase

**Comment by ryanjulian** [comment]
You might want to try this again once #1196 is in (or try it locally)

**Comment by ryanjulian** [comment]
@lywong92 do you think this is ready to be merged?

**Comment by ryanjulian** [comment]
I just marked this for merge. We'll see how it goes in the wild.

**Pull request merged**
