### PR TITLE
Remove Sawyer Files

### LINKED ISSUE #330: Move Sawyer environments and contrib.ros to a different repository
The following Sawyer environments need to be updated to be compatible with their parent class SawyerEnv:
- garage/envs/mujoco/sawyer/bin_sorting_env.py
- garage/envs/mujoco/sawyer/block_stacking_env.py
- garage/envs/mujoco/sawyer/reacher_env.py
- garage/envs/mujoco/sawyer/sawyer_env.py

For example, now SawyerEnv requires an instance of the Configuration class as parameter for the start_goal_config, instead of the parameters initial_goal and intial_qpos.
Another more hidden issues need to be solved. For example, there seems to be an array size problem for BinSortingEnv when the method set_gripper_state in SawyerEnv gets called.
This issue also requires of tests to verify that the environments mentioned above can be instantiated and serialized (pickled).

### PR DESCRIPTION
**Pull request by utkarshjp7**
The PR fixes #330.

Removed following files and folders.
- envs/mujoco/sawyer
- contrib/ros
- tests/garage/envs/mujoco/sawyer
- examples/theano/trpo_sawyer_reacher.py

### CODE REVIEW

**Comment by ryanjulian** [comment]
Please make sure we can run these environments in the other repo(from garage) before submitting this change.

**Comment by utkarshjp7** [comment]
The build is failing because some commit messages are not capitalized. 
@ryanjulian Can I close this one and create another pull request with capitalized commit messages?

**Comment by ryanjulian** [comment]
Use `git rebase -i master` to rewrite your commit messages.

**Comment by ryanjulian** [comment]
Please read CONTRIBUTING.md about why you shouldn't use `git merge` or merge commits.

**Pull request merged**
