### PR TITLE
Update GCC to avoid build errors

### PR DESCRIPTION
**Pull request by gonzaiva**
In OSX 10.14 there are build errors for dm-control due to gcc 7 which
invalidates the installation of the conda environment for garage. This
is solved by upgrading to the latest version of gcc, and it was tested
in both OSX 10.12 and 10.14.

### CODE REVIEW

**Comment by CatherineSue** [comment]
Yes the default is now gcc@8 I believe. I tried gcc@7, it doesn't work on 10.14, but gcc@8 works. gcc@8 also works on 10.12. I haven't tested on 10.13.

**Comment by ryanjulian** [comment]
I'm willing to bet gcc@8 works in 10.13 if it works on 10.12.

Don't forget to update the known-good versions

**Comment by gautams3** [comment]
scripts/setup_osx.sh has been renamed to setup_macos.sh. Rebase off of master and push

**Comment by ryanjulian** [comment]
Please get this submitted ASAP since we want it in the release

**Pull request merged**
